### ISSUE TITLE
incorrect minimum value display

### ISSUE THREAD

**Issue by dukeduck1984** [larsmars/vuejs-thermometer#8]
Hi Lars,

When I set the min property to a value which is greater than zero, the displayed minimum value on the thermometer will be incorrect - e.g. if I set :min="10", the displayed min value will be -9; if set min to 5, the displayed min value will be -5.

Kaiyuan

**Comment by dukeduck1984** [comment]
it may be caused by the tick step calculation

`tickStep () {
      return (Math.abs(this.min) + Math.abs(this.max)) / (this.defaultOptions.thermo.ticks - 1)
    },`

Shouldn't it be
`tickStep () {
      return (Math.abs(this.max - this.min)) / this.defaultOptions.thermo.ticks
    },`

**Comment by dukeduck1984** [comment]
`
tickStep () {
      return (Math.abs(this.max - this.min)) / (this.defaultOptions.thermo.ticks - 1)
    },
ticks () {
      let ticks = []
      let maxValue = this.max
      for (let i = 0; i < (this.defaultOptions.thermo.ticks - 1); i++) {
        ticks.push(Math.round(maxValue))
        maxValue -= this.tickStep
      }
      ticks.push(this.min)
      return ticks
    },
`
I edited above code so that both max & min values displayed will be exactly same as set in the property, also the above mentioned issue is fixed.

**Comment by larsmars** [comment]
Thank you for the input, repo updated :)
